#!/bin/sh

IFCONFIG=/sbin/ifconfig
BASE_OID=".1.3.6.1.2.1.31.1.1.1.18"

get_ifinfo() {
    netstat -i | fgrep 'Link#' | sed 's/[\#\>]/ /g' | awk '{ print $4, $1; }'
}

get_descr()
{
    ifconfig $1 | awk '/description:/ {print $2}'
}

get_next_index() {
    CURRENT_INDEX=$1
    get_ifinfo | awk -v current="$CURRENT_INDEX" '$1 > current {print $1}' | head -n 1
}


while read CMD; do
    case "$CMD" in
        PING)
            echo "PONG"
            ;;
        get)
            read OID
            INDEX=${OID##*.}
            IFNAME=$(get_ifinfo | awk -v idx="$INDEX" '($1 == idx) {print $2;}')
            if [ -n "$IFNAME" ]; then
                DESC=$(get_descr $IFNAME)
                echo "$OID"
                echo "string"
                echo "$DESC"
            else
                echo "NONE"
            fi
            ;;
        getnext)
            read OID
            if [ "$OID" = "$BASE_OID" ] || [ -z "$OID" ]; then
                NEXT_INDEX=$(get_ifinfo | head -n 1 | awk '{print $1}')
            else
                CURRENT_INDEX=${OID##*.}
                NEXT_INDEX=$(get_next_index "$CURRENT_INDEX")
            fi

            if [ -n "$NEXT_INDEX" ]; then
                IFNAME=$(get_ifinfo | awk -v idx="$NEXT_INDEX" '($1 == idx) {print $2;}')
                DESC=$(get_descr $IFNAME)
                echo "$BASE_OID.$NEXT_INDEX"
                echo "string"
                echo "$DESC"
            else
                echo "NONE"
            fi
            ;;
        *)
            echo "NONE"
            ;;
    esac
done
